# Status
set -g status-interval 1
set -g escape-time 10
set -g repeat-time 500
set -g display-time 1500

# Set default terminal to support 256 colors
set -g default-terminal "tmux-256color"
set -sag terminal-features ",*:RGB"
set -sag terminal-features ",*:usstyle"


set -g focus-events on

# Core Options
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Do not detach when destroying a session
set -g detach-on-destroy off
# Change prefix key to C-z
unbind C-b
set -g prefix C-z
bind C-z send-prefix

# Enable mouse mode
set -g mouse on

# Pane Navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Reload Configuration
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Window Navigation
bind-key -n C-Left previous-window
bind-key -n C-Right next-window

# Panes
bind -r S-Left resize-pane -L 5
bind -r S-Down resize-pane -D 5
bind -r S-Up resize-pane -U 5
bind -r S-Right resize-pane -R 5

bind -r \] swap-pane -D
bind -r \[ swap-pane -U
bind -r space select-layout -n

# List sessions with Prefix + w
bind-key x choose-tree -s
bind-key w kill-window
bind-key q kill-pane
# Split windows
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Configure Resurrect and Continuum
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

# Configure Catppuccin
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_status_background "none" # none == default
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# Initialize TPM (Tmux Plugin Manager)
run '~/.tmux/plugins/tpm/tpm'

# Status bar appearance
set -g status-position top
set -g status-justify centre
set -g status-left-length 80
set -g status-right-length 80

# Status Left: Session and current command
set -g status-left "#[fg=#{@thm_green},bg=default,bold]  #S #[fg=#{@thm_overlay_0},none]| #[fg=#{@thm_maroon},bg=default]  #{pane_current_command} "

# Status Right: Current path (truncated)
set -g status-right "#[fg=#{@thm_blue},bg=default]  #{=/24/...:#{b:pane_current_path}} "

# Window Status Format (Centered)
set -gF window-status-separator "#[fg=#{@thm_overlay_0}] "
set -g window-status-format " #I:#W "
set -g window-status-style "fg=#{@thm_rosewater},bg=default"
set -g window-status-last-style "fg=#{@thm_peach}"
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "fg=#{@thm_peach},bold,reverse"

# # pane border look and feel
setw -g pane-border-status off
setw -g pane-border-format ""
setw -g pane-active-border-style "bg=default,fg=#{@thm_peach}"
setw -g pane-border-style "bg=default,fg=#{@thm_overlay_1}"
setw -g pane-border-lines single

# Smart pane switching with awareness of Vim splits
bind-key -n C-h if-shell "[ -n '#{pane_current_command}' ] && [[ #{pane_current_command} =~ nvim ]]" { send-keys C-h } { select-pane -L }
bind-key -n C-j if-shell "[ -n '#{pane_current_command}' ] && [[ #{pane_current_command} =~ nvim ]]" { send-keys C-j } { select-pane -D }
bind-key -n C-k if-shell "[ -n '#{pane_current_command}' ] && [[ #{pane_current_command} =~ nvim ]]" { send-keys C-k } { select-pane -U }
bind-key -n C-l if-shell "[ -n '#{pane_current_command}' ] && [[ #{pane_current_command} =~ nvim ]]" { send-keys C-l } { select-pane -R }
