## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# The basic colors
foreground              #ffffff
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #ffffff

# Cursor colors
cursor                  #89b4fa
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #cdd6f4

# Kitty window border colors
active_border_color     #89b4fa
inactive_border_color   #89b4fa
bell_border_color       #89b4fa

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1E1E2E
active_tab_background   #89b4fa
inactive_tab_foreground #cdd6f4
inactive_tab_background #313244
tab_bar_background      #1E1E2E

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #89b4fa
mark2_foreground #1E1E2E
mark2_background #89b4fa
mark3_foreground #1E1E2E
mark3_background #89b4fa

# The 16 terminal colors

# black
color0 #1E1E2E
color8 #313244

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #74c7ec
color12 #74c7ec

# magenta
color5  #cba6f7
color13 #cba6f7

# cyan
color6  #89dceb
color14 #89dceb

# white
color7  #cdd6f4
color15 #ffffff
